version: '3.8'
services:
  sidekiq:
    image: sidekiq-prod
    build:
      context: .
      dockerfile: Dockerfile_sidekiq
    env_file:
      - .env.production

  web:
    image: prod
    build:
      context: .
      dockerfile: Dockerfile_web
    env_file:
      - .env.production
    ports:
      - "80:3000"
      - "443:3000"
